
import { Tender, TenderStatus, InventoryItem } from './types';

// Helper to set deadlines relative to now for the timer demo
const now = new Date();
const addDays = (days: number) => new Date(now.getTime() + days * 24 * 60 * 60 * 1000).toISOString().split('T')[0];
const addHours = (hours: number) => new Date(now.getTime() + hours * 60 * 60 * 1000).toISOString();

export const MOCK_TENDERS: Tender[] = [
  {
    id: 'T-53299355',
    title: 'Supply of Basmati Rice for Defense Canteens',
    authority: 'Army Service Corps (ASC)',
    region: 'Delhi / NCR',
    category: 'Grains & Pulses',
    deadline: addDays(45),
    estimatedQuantity: '500 MT',
    budget: '₹4.5 Crores',
    status: TenderStatus.OPEN,
    description: 'Procurement of Grade A Long-Grain Basmati Rice for multiple defense canteen depots across Northern India. Moisture content must be below 12%. Packaging in 50kg jute bags.',
    compliance: ['FSSAI License', 'GST Registration', 'ISO 22000', '3-Year Turnover Proof'],
    authorityTrait: 'Strict adherence to technical specifications; values logistics depth over lowest price.'
  },
  {
    id: 'T-8829102',
    title: 'Daily Procurement of Fresh UHT Milk',
    authority: 'Indian Railways - IRCTC',
    region: 'Maharashtra',
    category: 'Dairy',
    deadline: addDays(12),
    estimatedQuantity: '100,000 Liters/Month',
    budget: '₹60 Lakhs',
    status: TenderStatus.CLOSING_SOON,
    description: 'Supply of 500ml Tetrapaks of UHT treated milk. Shelf life minimum 6 months. Required for express train pantry services.',
    compliance: ['FSSAI License', 'Sterilization Certification', 'Cold Storage Logistics Proof'],
    authorityTrait: 'Highly price-sensitive; prefers concise executive summaries with clear unit-cost breakdowns.'
  },
  {
    id: 'T-112233',
    title: 'Bulk Supply of Edible Sunflower Oil',
    authority: 'Department of Food & Public Distribution',
    region: 'Karnataka',
    category: 'Oils & Fats',
    deadline: addDays(3),
    estimatedQuantity: '200 MT',
    budget: '₹2.8 Crores',
    status: TenderStatus.OPEN,
    description: 'Fortified Sunflower oil for distribution under PDS scheme. High quality refined oil required with Vitamin A and D fortification.',
    compliance: ['FSSAI License', 'Fortification Certificate', 'Pollution Control NOC'],
    authorityTrait: 'Compliance-heavy requirements; values detailed risk mitigation strategies for supply disruptions.'
  },
  {
    id: 'T-445566',
    title: 'Instant Coffee & Tea Premixes for PSU Offices',
    authority: 'Oil & Natural Gas Corporation (ONGC)',
    region: 'Gujarat',
    category: 'Beverages',
    deadline: addHours(1.5),
    estimatedQuantity: '5,000 Kg',
    budget: '₹15 Lakhs',
    status: TenderStatus.OPEN,
    description: 'Premixes for automated vending machines. Sugar-free variants also required. Annual rate contract format.',
    compliance: ['FSSAI License', 'Sample Testing Approval', 'MSME Registration (Preferred)'],
    authorityTrait: 'Values innovation and premium quality; prefers sample-led technical pitches.'
  },
  {
    id: 'T-991022',
    title: 'Whole Spices Supply for Central Police Canteens',
    authority: 'Central Police Canteen (CPC)',
    region: 'All India',
    category: 'Spices & Condiments',
    deadline: addDays(25),
    estimatedQuantity: '50 MT',
    budget: '₹1.2 Crores',
    status: TenderStatus.OPEN,
    description: 'Supply of high-quality Black Pepper, Turmeric, and Cumin seeds. Must be free from adulterants and meet Agmark Grade 1 standards.',
    compliance: ['Agmark Grade 1', 'FSSAI License', 'Import/Export Code (if applicable)'],
    authorityTrait: 'Purity focused; uses independent lab testing for every batch. Zero tolerance for quality deviations.'
  },
  {
    id: 'T-773322',
    title: 'Annual Contract for Packaged Drinking Water',
    authority: 'Air India SATS',
    region: 'Karnataka',
    category: 'Beverages',
    deadline: addDays(8),
    estimatedQuantity: '1,000,000 Bottles (500ml)',
    budget: '₹90 Lakhs',
    status: TenderStatus.OPEN,
    description: 'Supply of 500ml PET bottles for in-flight catering. Brand visibility and eco-friendly packaging are priorities.',
    compliance: ['BIS Certification', 'FSSAI License', 'Plastic Waste Management Plan'],
    authorityTrait: 'Brand conscious; looks for partners with strong environmental, social, and governance (ESG) commitments.'
  },
  {
    id: 'T-554411',
    title: 'Cleaning & Hygiene Kits for Municipal Staff',
    authority: 'Greater Mumbai Municipal Corporation (MCGM)',
    region: 'Maharashtra',
    category: 'Home Care',
    deadline: addDays(15),
    estimatedQuantity: '20,000 Kits',
    budget: '₹40 Lakhs',
    status: TenderStatus.OPEN,
    description: 'Kits containing Soap, Sanitizer, and Floor Cleaners for sanitation workers. Bulk packaging preferred for easy distribution.',
    compliance: ['Drug License (Sanitizer)', 'FSSAI (if applicable)', 'ISO 9001'],
    authorityTrait: 'Logistics driven; requires evidence of last-mile distribution capabilities in urban slums.'
  },
  {
    id: 'T-667788',
    title: 'Supply of Premium Tea Dust for Railway Staff',
    authority: 'Northern Railways',
    region: 'Uttar Pradesh',
    category: 'Beverages',
    deadline: addDays(10),
    estimatedQuantity: '10,000 Kg',
    budget: '₹25 Lakhs',
    status: TenderStatus.OPEN,
    description: 'Strong aroma CTC Tea Dust required for staff canteens. Vacuum packed in 1kg industrial grade foil bags.',
    compliance: ['FSSAI License', 'Tea Board Registration', 'GST Compliance'],
    authorityTrait: 'Favors established regional players; high weightage for consistent flavor profile.'
  },
  {
    id: 'T-121212',
    title: 'Bulk Fortified Wheat Flour (Atta) Procurement',
    authority: 'State Welfare Dept - Bihar',
    region: 'Bihar',
    category: 'Grains & Pulses',
    deadline: addDays(5),
    estimatedQuantity: '2,000 MT',
    budget: '₹6 Crores',
    status: TenderStatus.CLOSING_SOON,
    description: 'High-fiber whole wheat flour fortified with Iron, Folic Acid, and Vitamin B12. Distribution through state fair price shops.',
    compliance: ['FSSAI License', 'Fortification Unit Approval', 'Turnover > 10Cr'],
    authorityTrait: 'Urgent procurement needs; delivery timeline is the primary scoring metric.'
  },
  {
    id: 'T-343434',
    title: 'Kachchi Ghani Mustard Oil Supply',
    authority: 'Border Security Force (BSF)',
    region: 'Rajasthan',
    category: 'Oils & Fats',
    deadline: addDays(30),
    estimatedQuantity: '150 MT',
    budget: '₹1.8 Crores',
    status: TenderStatus.OPEN,
    description: 'Cold-pressed mustard oil with high pungency level. Purity certification from NABL accredited lab mandatory.',
    compliance: ['FSSAI License', 'NABL Lab Report', 'Agmark Certification'],
    authorityTrait: 'Values supply chain integrity; physical verification of cold-press units likely.'
  },
  {
    id: 'T-898989',
    title: 'Skimmed Milk Powder for Nutrition Program',
    authority: 'ICDS - Ministry of Women & Child Development',
    region: 'Madhya Pradesh',
    category: 'Dairy',
    deadline: addDays(20),
    estimatedQuantity: '300 MT',
    budget: '₹8.5 Crores',
    status: TenderStatus.OPEN,
    description: 'Spray-dried skimmed milk powder for Anganwadi centers. Protein content minimum 34%. Free from any additives.',
    compliance: ['FSSAI License', 'BIS Marking', 'Export/Import Code (if relevant)'],
    authorityTrait: 'Sensitive to public health impact; zero tolerance for microbial contamination.'
  },
  {
    id: 'T-454545',
    title: 'Mango Pulp & Fruit Concentrates for In-flight',
    authority: 'Indigo Catering Services',
    region: 'All India',
    category: 'Beverages',
    deadline: addDays(14),
    estimatedQuantity: '25,000 Liters',
    budget: '₹45 Lakhs',
    status: TenderStatus.OPEN,
    description: 'Alphonso and Totapuri mango pulp for seasonal beverage preparations. Natural variants only, no added sugar preferred.',
    compliance: ['FSSAI License', 'HACCP Certification', 'FSSC 22000'],
    authorityTrait: 'Quality and Brand alignment focus; prefers long-term partnership over spot-buy price.'
  },
  {
    id: 'T-909090',
    title: 'Annual Supply of Red Chilli & Turmeric Powder',
    authority: 'ITBP Canteens',
    region: 'Uttarakhand',
    category: 'Spices & Condiments',
    deadline: addDays(40),
    estimatedQuantity: '40 MT',
    budget: '₹85 Lakhs',
    status: TenderStatus.OPEN,
    description: 'Grade 1 Red Chilli powder (High Heat) and Turmeric powder (Curcumin > 3%). Packaging in moisture-proof 5kg bags.',
    compliance: ['FSSAI License', 'Spices Board Certificate', 'Agmark'],
    authorityTrait: 'High-altitude logistics capable vendors preferred; value focus on shelf-life stability.'
  },
  {
    id: 'T-676767',
    title: 'Eco-friendly Floor Cleaners for Govt Schools',
    authority: 'Dept of School Education - TN',
    region: 'Tamil Nadu',
    category: 'Home Care',
    deadline: addDays(7),
    estimatedQuantity: '50,000 Liters',
    budget: '₹30 Lakhs',
    status: TenderStatus.CLOSING_SOON,
    description: 'Bio-degradable, herbal-based floor cleaners. Non-toxic, safe for use in primary school environments.',
    compliance: ['Pollution Control Board NOC', 'MSME Registration', 'ISO 14001'],
    authorityTrait: 'ESG and social impact driven; prefers MSME and local women-led enterprises.'
  },
  {
    id: 'T-232323',
    title: 'Organic Bajra & Millets for Canteens',
    authority: 'Rajasthan State Food Corp',
    region: 'Rajasthan',
    category: 'Grains & Pulses',
    deadline: addDays(55),
    estimatedQuantity: '100 MT',
    budget: '₹55 Lakhs',
    status: TenderStatus.OPEN,
    description: 'Certified Organic Pearl Millet (Bajra) and Ragi. Promoting millet consumption under International Year of Millets initiative.',
    compliance: ['NPOP/PGS Organic Certificate', 'FSSAI License'],
    authorityTrait: 'Policy aligned; favors vendors with direct farmer-procurement certifications.'
  },
  {
    id: 'T-151515',
    title: 'Compressed Green Tea & Herbal Infusions',
    authority: 'Parliament House Estate',
    region: 'Delhi',
    category: 'Beverages',
    deadline: addDays(18),
    estimatedQuantity: '2,000 Boxes',
    budget: '₹12 Lakhs',
    status: TenderStatus.OPEN,
    description: 'Assorted herbal tea bags including Ashwagandha and Tulsi variants. Premium wooden packaging for VIP gifting.',
    compliance: ['FSSAI License', 'Tea Board Organic Cert'],
    authorityTrait: 'Excellence in packaging and presentation is mandatory; technical evaluation is strictly sample-based.'
  },
  {
    id: 'T-787878',
    title: 'Washing Powder & Dishwash Gel for CRPF',
    authority: 'Central Reserve Police Force (CRPF)',
    region: 'All India',
    category: 'Home Care',
    deadline: addDays(22),
    estimatedQuantity: '200 MT',
    budget: '₹1.5 Crores',
    status: TenderStatus.OPEN,
    description: 'High-efficiency washing powder and anti-bacterial dishwash gel. Required for multiple group centers across India.',
    compliance: ['BIS Standards', 'ISO 9001', 'GST Registration'],
    authorityTrait: 'Massive volume logistics experience is the key differentiator for this contract.'
  }
];

export const MOCK_INVENTORY: InventoryItem[] = [
  { id: 'inv-1', name: 'Basmati Rice (Long Grain)', availableQty: 600, unit: 'MT' },
  { id: 'inv-2', name: 'UHT Milk (500ml Tetrapak)', availableQty: 45000, unit: 'Units' },
  { id: 'inv-3', name: 'Sunflower Oil (Refined)', availableQty: 250, unit: 'MT' },
  { id: 'inv-4', name: 'Tea Premix (Classic)', availableQty: 12000, unit: 'Kg' },
  { id: 'inv-5', name: 'Whole Spices (Assorted)', availableQty: 75, unit: 'MT' },
  { id: 'inv-6', name: 'Drinking Water (500ml PET)', availableQty: 250000, unit: 'Units' },
  { id: 'inv-7', name: 'Hygiene Kits (Standard)', availableQty: 5000, unit: 'Kits' },
  { id: 'inv-8', name: 'Premium Tea Dust', availableQty: 15000, unit: 'Kg' },
  { id: 'inv-9', name: 'Fortified Wheat Flour', availableQty: 500, unit: 'MT' },
  { id: 'inv-10', name: 'Mustard Oil (Cold Pressed)', availableQty: 200, unit: 'MT' },
  { id: 'inv-11', name: 'Skimmed Milk Powder', availableQty: 400, unit: 'MT' },
  { id: 'inv-12', name: 'Mango Pulp (Concentrate)', availableQty: 30000, unit: 'Liters' },
  { id: 'inv-13', name: 'Floor Cleaner (Herbal)', availableQty: 12000, unit: 'Liters' },
  { id: 'inv-14', name: 'Organic Millets (Assorted)', availableQty: 150, unit: 'MT' },
  { id: 'inv-15', name: 'Washing Powder (Bulk)', availableQty: 300, unit: 'MT' }
];

export const COMPANY_PROFILE = {
  name: 'AgroPrime Solutions Pvt Ltd',
  specialization: 'Large-scale FMCG distribution and food processing',
  turnover: '₹50 Crores annually',
  experience: '12 years in government supply chains',
  certificates: ['FSSAI Platinum', 'ISO 9001', 'ISO 22000', 'Agmark Certified'],
  warehouses: ['Delhi (Hub)', 'Mumbai (Regional)', 'Bengaluru (Logistics Center)'],
  fleetSize: '45 Temperature-controlled Trucks',
  keyClients: ['Defense Ministry', 'Indian Railways', 'UNICEF Food Program']
};
